createStaticContent:
    path:     /staticcontent/new
    defaults: { _controller: AppFrontendBundle:StaticContent:create }

validateStaticContent:
    path:     /ajax/createStaticContent/
    defaults: { _controller: AppFrontendBundle:StaticContent:validateCreation }

editStaticContent:
    path:   /staticcontent/edit/{id}
    defaults: { _controller: AppFrontendBundle:StaticContent:edit }
    
validateEditStaticContent:
    path:     /ajax/updateStaticContent/
    defaults: { _controller: AppFrontendBundle:StaticContent:validateEdit }

getStaticContent:
    path:     /ajax/getStaticContent/{id}
    defaults: { _controller: AppFrontendBundle:StaticContent:get }
    
registerAccount:
    path:     /account/register
    defaults: { _controller: AppFrontendBundle:User:register }
    
loginAccount:
    path:     /account/login
    defaults: { _controller: AppFrontendBundle:User:login }
    
loginCheckAccount:
    path:     /ajax/login
    defaults: { _controller: AppFrontendBundle:User:loginConfirm }
    
registerLoggedUser:
    path:     /ajax/registerlogged
    defaults: { _controller: AppFrontendBundle:User:registerLoggedUser }
    
logout:
    path:     /ajax/logout
    defaults: { _controller: AppFrontendBundle:User:logout }